version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: anvil-test-all-postgres
    environment:
      POSTGRES_DB: anvil_test
      POSTGRES_USER: anvil_user
      POSTGRES_PASSWORD: anvil_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432" # Use different port to avoid conflicts
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U anvil_user -d anvil_test" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - anvil-test-network

  anvil-test-all:
    build:
      context: .
      dockerfile: Dockerfile.test-all
    container_name: anvil-test-all-runner
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database configuration
      DATABASE_URL: "postgresql://anvil_user:anvil_password@postgres:5432/anvil_test"
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: anvil_test
      PGUSER: anvil_user
      PGPASSWORD: anvil_password

      # Anvil configuration
      ANVIL_SERVER_URL: localhost
      ANVIL_SERVER_PORT: 3030
      NEXT_PUBLIC_WEBSOCKET_URL: ws://localhost:3001
      NEXT_PUBLIC_ANVIL_SERVER_URL: http://localhost:3030

      # Test configuration
      NODE_ENV: test
      CI: true
      DOCKER_ENV: true
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
      PLAYWRIGHT_DISABLE_WEB_SERVER: 1

      # Display for headless browser
      DISPLAY: ":99"

    ports:
      - "3000:3000" # NextJS
      - "3001:3001" # WebSocket bridge
      - "3030:3030" # Anvil server
    volumes:
      - ./test-results:/app/test-results
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./tools:/app/tools:ro
    networks:
      - anvil-test-network
    command: >
      sh -c "
        echo '🚀 Starting Comprehensive Anvil-NextJS Test Suite...' &&
        echo '📋 Waiting for PostgreSQL to be ready...' &&
        until pg_isready -h postgres -U anvil_user; do sleep 1; done &&
        echo '✅ PostgreSQL is ready' &&
        echo '🧪 Running All Tests...' &&
        npm run test:all:docker
      "

volumes:
  postgres_test_data:


networks:
  anvil-test-network:
    driver: bridge
